<div class="container">
         
         <div class="about">             
            <h2>Projet Finale</h2>
            <h2>Formation développeur intégrateur web</h2>
            <p>3W Academy</p>
            <p>Adresse:  46 Rue René Clair, 75018 Paris</p>
            <p>Téléphone :  01 75 43 42 42</p>
            <p>Réalisé par</p>
            <p>Bruno Soares</p>
            <h2>REMERCIEMENTS</h2>
            <p>Tout d’abord, nous tenons à remercier tout particulièrement et à témoigner toute ma
    reconnaissance &agrave; tous les formateurs, équipe pédagogique et &agrave; tous et &agrave; toutes colegues de salle pour leur dévouement et leur soutient dans la
    concrétisation de ce projet.</p>       
         </div>
     </div>