<img src="<?= $wwwUrl ?>/images/home.jpeg">
<p>Un code peut désigner:

un ensemble de règles de comportement, pratiques ou conventions en société, formalisées ou non (ex : code vestimentaire)
    un document (livre ou autre) où ces règles sont rédigées (ex : code minier)
une règle algorithmique pour convertir des morceaux de donnée sous une autre forme ou représentation, éventuellement à des fins de confidentialité (ex: sélection de la première lettre de chaque mot)
    le résultat de l'application de cette règle à une information.

Le mot « code » vient du mot latin codex, qui désigne un format d'écrit, de taille parallélépipédique et constitué de pages reliées entre elles. </p>