
        <div class="container">
          <form class="form-group" action="<?= $requestUrl ?>/phpmailer" method="post">
            <div>
              <label>Votre nom</label>
              <input type="text" name="nom" id="nom" class="form-control" placeholder="Non" required/>
              <label>Email</label>
              <input type="email" name="email" id="email" class="form-control" placeholder="votre.email@email.com"  required/>
              <label>Message</label>
              <textarea id="content" name="message" placeholder="Votre message ici..." required class="form-control"></textarea>  
            </div>
            <div class="btn-summetre">
              <input type="submit" value="Summetre" class="btn btn-success" />
            </div>
            </form>
            <h5>&nbsp;&nbsp;Adresse: 39 rue de Paris, 78610 Le Perray en Yvelines.</h5> 
          </div>
          <div class="container-fluid">                
            <div>
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2633.5104792429142!2d1.8529849514264758!3d48.695723179170166!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e4277af2099eed%3A0xd0baa765a98e80b9!2s39%20Rue%20de%20Paris%2C%2078610%20Le%20Perray-en-Yvelines!5e0!3m2!1sfr!2sfr!4v1580251827392!5m2!1sfr!2sfr" width="100%" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
      
            </div>
          </div>    
