
	


		 <section>
	 
				<fieldset>
					<legend>Connexion</legend>								
						<form action="<?= $requestUrl ?>/login" method="post" class="form-group">					
							<label for="uname"><b>Email</b></label>
							<input class="form-control" type="email" placeholder="Enter Email" name="email" required>                 
							<label for="psw"><b>Mot de passe</b></label>
							<input class="form-control" type="password" placeholder="Enter Password" name="password" required>                        
							<div><hr></div>	
							<button type="submit" class="btn btn-success" >Login</button>              
						</form>					
				</fildset>

        </section>
